stages:
  - build
  - deploy
  - development
.deploy-dev:
  stage: development
  services:
    - kroniak/ssh-client
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -tt good@45.118.132.204 "cd jarvan/ && git pull && make compose_dev"

deploy:development:
  extends: .deploy-dev
  variables:
    HOST: ${STG_HOST}
    SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY_STG}
    GO_PATH: backend/joon
    COMMAND: make compose_dev
    BRANCH: develop
    SERVER_ENV: dev
  only:
    - development