version: '1.0.0'
services:
  j4:
    container_name: jarvancrawler
    image: "jarvancrawler:0.0.1"
    hostname: jarvancrawler.local
    restart: always
    environment:
      - APP_ENV=env
      - PORT=9001
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=547436
      - DB_NAME=jarvan
      - ENABLE_DB=true
    ports:
      - "9001:9001"
  postgresdb:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=547436
      - POSTGRES_DB=jarvan
    ports:
      - 5432:5432