version: '1.0.0'
services:
  j4:
    container_name: jarvancrawler
    image: "jarvancrawler:0.0.1"
    hostname: jarvancrawler.local
    restart: always
    depends_on:
      - postgresdb
    ports:
      - "9001:9001"
    networks:
      - meracrawler
    volumes:
      - ./.env:/app/.env

  postgresdb:
    container_name: postgresdb
    image: postgres:15.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=547436
      - POSTGRES_DB=jarvan
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      meracrawler:
        ipv4_address: 172.16.238.10

networks:
  meracrawler:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
